### ISSUE TITLE
Using with Istanbul harmony

### ISSUE THREAD

**Issue by tbranyen** [leobalter/goiabada#6]
istanbul (code coverage tool) has a harmony branch and it'd be cool to investigate usage with this test runner.

**Comment by leobalter** [comment]
Currently I just pushed istanbul against the non-harmony files, I'll try to evolve it to call the es2015 one.

**Comment by leobalter** [comment]
> Istanbul doesn't yet support arrow functions even in the harmony branch

https://github.com/gotwarlost/istanbul/issues/329#issuecomment-83319549

Currently, the coverage is being measured against the modules processed via babel.

**Comment by leobalter** [comment]
I'll reopen this when they got to support ES6 features.
